### ISSUE TITLE
poznamky zo stretnutia so zadavatelom

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2022-FMFI/lessons#1]
poslat zadavatelovi na pripadne doplnenie a kontrolu

**Comment by 1Andrea0** [comment]
Zadávateľ bol mimo Slovenska a dostupný bude až vo štvrtok (13.10.), preto poznámky sú spísané aj poslané na kontrolu, no vyjadrenie od zadávateľa bude k dispozícii až neskôr.

[zapisnica1.txt](https://github.com/TIS2022-FMFI/lessons/files/9748067/zapisnica1.txt)

**Comment by 1Andrea0** [comment]
![Image](https://user-images.githubusercontent.com/99814501/196394568-22da9227-c617-40b4-bd8f-0463980f606c.png)
