### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by xEvickA** [TIS2022-FMFI/lessons#10]

**Comment by VojtekJakub** [comment]
![Image](https://user-images.githubusercontent.com/100524780/205762740-852c5aca-6f2d-4f76-a239-388851b0c339.png)

 variacia s edit a delete problem. (treba upravit kvoli nezhode required a provided interface-ov v search engine ale nikde som na internete nenasiel mazanie a editovanie tak som to nechal takto zatial)
