### ISSUE TITLE
UML class diagram

### ISSUE THREAD

**Issue by xEvickA** [TIS2022-FMFI/lessons#11]

**Comment by xEvickA** [comment]
![image](https://user-images.githubusercontent.com/99814623/204014755-f013030e-0527-496b-8a7e-51e939a5feaf.png)

**Comment by pavelpetrovic** [comment]
![Image](https://user-images.githubusercontent.com/13798920/204543220-549401de-d40d-4f7a-8636-cc2e90ad9a92.png)
