### ISSUE TITLE
katalog poziadaviek

### ISSUE THREAD

**Issue by 1Andrea0** [TIS2022-FMFI/lessons#2]
[Katalóg požiadaviek2.pdf](https://github.com/TIS2022-FMFI/lessons/files/9748076/Katalog.poziadaviek2.pdf)

**Comment by pavelpetrovic** [comment]
je to verzia, ktoru si uz mam pozriet, pls?

**Comment by 1Andrea0** [comment]
áno, aby sme sa mali o čom zajtra rozprávať

**Comment by pavelpetrovic** [comment]
mojich par komentarov v dokumente

[Katalóg požiadaviek2 (1).docx](https://github.com/TIS2022-FMFI/lessons/files/9755943/Katalog.poziadaviek2.1.docx)

**Comment by 1Andrea0** [comment]
opravený katalóg požiadaviek

[Katalóg požiadaviek3.docx](https://github.com/TIS2022-FMFI/lessons/files/9808950/Katalog.poziadaviek3.docx)

**Comment by pavelpetrovic** [comment]
par pripomienok este 
[Katalog.poziadaviek3(1).docx](https://github.com/TIS2022-FMFI/lessons/files/9810543/Katalog.poziadaviek3.1.docx)

**Comment by 1Andrea0** [comment]
opravený katalóg požiadaviek

[Katalóg požiadaviek4.docx](https://github.com/TIS2022-FMFI/lessons/files/9833428/Katalog.poziadaviek4.docx)

**Comment by pavelpetrovic** [comment]
mierne upravy, pre nas finalna verzia, nasleduje iteracia so zadavatelom

[Katalog.poziadaviek4_upraveny.docx](https://github.com/TIS2022-FMFI/lessons/files/9860349/Katalog.poziadaviek4_upraveny.docx)

**Comment by 1Andrea0** [comment]
finálna verzia

[Katalog.poziadaviek5.docx](https://github.com/TIS2022-FMFI/lessons/files/9953895/Katalog.poziadaviek5.docx)

**Comment by 1Andrea0** [comment]
iba upravené slová (ruby -> java, webová aplikácia -> desktopová aplikácia)


[Katalog.poziadaviek6.docx](https://github.com/TIS2022-FMFI/lessons/files/10012418/Katalog.poziadaviek6.docx)

**Comment by 1Andrea0** [comment]
![Image](https://user-images.githubusercontent.com/99814501/203654904-0d34f28a-9d3a-4cd5-8937-51887ffd8b0e.jpg)
