### ISSUE TITLE
Vytvorenie návrhu používateľského rozhrania

### ISSUE THREAD

**Issue by xEvickA** [TIS2022-FMFI/lessons#4]

**Comment by JakubMurin** [comment]
Menu
![Image](https://user-images.githubusercontent.com/83812290/204522143-afbe1de9-a33e-497d-a5c3-7bdb293dc6fd.png)

Dialog window with detail of lesson
![Image](https://user-images.githubusercontent.com/83812290/204522142-23cb5d53-ec66-42e3-ab81-7aca347404ab.png)

**Comment by JakubMurin** [comment]
Update

Menu
![ui](https://user-images.githubusercontent.com/83812290/207335991-dd55b22c-d5ae-475b-9f6e-d545e09ce583.png)

New lesson form
![form](https://user-images.githubusercontent.com/83812290/207287013-d9bdb7be-978a-45cb-87b3-64f3a6319ac2.png)

Show lesson dialog
![ui_dialog](https://user-images.githubusercontent.com/83812290/207287111-aca82259-9993-44f8-a96c-0ccd100da229.png)
