### ISSUE TITLE
Vytvorenie dátového modelu

### ISSUE THREAD

**Issue by xEvickA** [TIS2022-FMFI/lessons#6]

**Comment by xEvickA** [comment]
[datovymodel.docx](https://github.com/TIS2022-FMFI/lessons/files/9953840/datovymodel.docx)

**Comment by xEvickA** [comment]
[datovy mode.docx](https://github.com/TIS2022-FMFI/lessons/files/10012627/datovy.mode.docx)

**Comment by xEvickA** [comment]
![image](https://user-images.githubusercontent.com/99814623/204015071-86a3e6d9-fbfb-4533-b52b-bf183204f9b9.png)

**Comment by pavelpetrovic** [comment]
![Image](https://user-images.githubusercontent.com/13798920/204542511-cbae0322-49a2-42c2-9784-e4c86577aa96.png)
